In [1]:
#01 Explore Data
print("hello pork")

hello pork


In [5]:
from PIL import Image
image = Image.open("../data/raw/frame_with_red_8669.jpg")

In [6]:
print("Image size:", image.size)
print("Image mode:", image.mode)

Image size: (1440, 1080)
Image mode: RGB


In [8]:
pixel = image.getpixel((100,100))
print(pixel)

(168, 175, 167)


In [10]:
import numpy as np
image_array = np.array(image)
print(image_array)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 24  32   9]
  [ 36  33  24]
  [ 40  35  31]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 28  32  17]
  [ 37  33  32]
  [ 41  35  39]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 32  32  30]
  [ 38  32  46]
  [ 42  32  56]]

 ...

 [[172 195 179]
  [171 191 179]
  [172 187 182]
  ...
  [ 56  45  61]
  [ 58  47  55]
  [ 58  47  51]]

 [[178 203 173]
  [178 201 175]
  [179 192 175]
  ...
  [ 56  45  62]
  [ 58  47  53]
  [ 61  50  48]]

 [[177 203 166]
  [184 205 172]
  [183 197 174]
  ...
  [ 56  45  62]
  [ 60  48  52]
  [ 62  51  47]]]


In [12]:
print(image_array.shape)

(1080, 1440, 3)


In [15]:
average_rgb = image_array.mean(axis=(0, 1))
print("Average RGB:", average_rgb)

Average RGB: [70.91456276 64.60105388 64.63373071]
